export const MAIN_ROUTE = '/'
export const CONTACT_ROUTE = '/contact'
export const ABOUT_ROUTE = '/about'
export const CINEMAS_ROUTE = '/cinemas'
export const MOVIE_ROUTE = '/movies/:id'
export const NOT_FOUND_ROUTE = '*'
