"""Add booking table

Revision ID: 446a6769b95f
Revises: decb12a2b2ef
Create Date: 2025-04-20 00:16:40.506596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '446a6769b95f'
down_revision: Union[str, None] = 'decb12a2b2ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('sessionId', sa.Integer(), nullable=True),
    sa.Column('seatId', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seatId'], ['seat.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sessionId'], ['session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('seat_userId_fkey', 'seat', type_='foreignkey')
    op.drop_column('seat', 'userId')
    op.drop_column('seat', 'isBooked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat', sa.Column('isBooked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('seat', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('seat_userId_fkey', 'seat', 'user', ['userId'], ['id'])
    op.drop_table('booking')
    # ### end Alembic commands ###
