"""Add user table

Revision ID: 98e4d65f3666
Revises: e767c5aa26fb
Create Date: 2025-03-31 17:31:22.659686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e4d65f3666'
down_revision: Union[str, None] = 'e767c5aa26fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seat', 'userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seat', 'userId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
