"""add hall table

Revision ID: c54309b22699
Revises: 758ddb813c10
Create Date: 2025-03-25 19:44:09.278711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54309b22699'
down_revision: Union[str, None] = '758ddb813c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hall',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'movie_genre', 'movie', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'movie_genre', 'genre', ['genre_id'], ['id'], ondelete='CASCADE')
    op.add_column('session', sa.Column('hallId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'session', 'hall', ['hallId'], ['id'], ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'hallId')
    op.drop_constraint(None, 'movie_genre', type_='foreignkey')
    op.drop_constraint(None, 'movie_genre', type_='foreignkey')
    op.drop_table('hall')
    # ### end Alembic commands ###
