"""Add user table and replaced fields

Revision ID: decb12a2b2ef
Revises: c54309b22699
Create Date: 2025-04-17 14:58:43.428285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'decb12a2b2ef'
down_revision: Union[str, None] = 'c54309b22699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('role', postgresql.ENUM('USER', 'ADMIN', name='role'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('seat',
    sa.Column('seatNumber', sa.Integer(), nullable=False),
    sa.Column('isBooked', sa.Boolean(), nullable=False),
    sa.Column('hallId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hallId'], ['hall.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hall', sa.Column('price', sa.Integer(), nullable=False))
    op.drop_constraint('session_hallId_fkey', 'session', type_='foreignkey')
    op.create_foreign_key(None, 'session', 'hall', ['hallId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.create_foreign_key('session_hallId_fkey', 'session', 'hall', ['hallId'], ['id'])
    op.drop_column('hall', 'price')
    op.drop_table('seat')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
